version: "3.9"

services:
  producer:
    build:
      context: ./backend
      dockerfile: ./build/docker/producer.Dockerfile
    container_name: producer
    depends_on:
      - zookeeper
      - kafka
    develop:
        watch:
            - action: rebuild
              files:
                - ./**/*.go
                - ./go.mod
                - ./go.sum

  consumer:
    build:
      context: ./backend
      dockerfile: ./build/docker/consumer.Dockerfile
    container_name: consumer
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8080:8080"
    expose:
      - 8080
    develop:
      watch:
        - action: rebuild
          files:
            - ./**/*.go
            - ./go.mod
            - ./go.sum

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    expose:
      - 9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1